[package]
name = "racr-compose"
version = "0.1.0"
authors = ["Kjetil Kjeka <kjetilkjeka@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.32", features = ["yaml"]}
svd-parser = "0.6.0"
racr = {git = "https://github.com/kjetilkjeka/racr-format.git", rev="bfcf10580057949c32d4e9a78078de21e166144a"}
inflections = "1.1"
